"use client";

import { memo } from "react";

export const WalletPreviewCanvas = memo(function WalletPreviewCanvas({
  ariaLabel,
  height,
  profile,
  svg,
  width,
}: {
  ariaLabel: string;
  height: number;
  profile: "APPLE_LEGACY" | "APPLE_IOS27" | "APPLE_WALLET" | "GOOGLE_WALLET";
  svg: string;
  width: number;
}) {
  return (
    <span
      aria-label={ariaLabel}
      className="wallet-preview-image-stack__canvas"
      data-wallet-profile={profile}
      data-preview-ready="true"
      role="img"
      style={{ aspectRatio: `${width} / ${height}` }}
    >
      <span
        aria-hidden="true"
        className="wallet-preview-image-stack__svg"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: The SVG is generated by the closed, browser-safe Wallet renderer.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </span>
  );
});
