import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { resolveProductionTemplateStampArtwork } from "../apps/api/src/programs/library-artwork.js";
import { composeProgramPreview } from "../apps/api/src/programs/preview-composer.js";
import { findProgramTemplate } from "../packages/contracts/src/index.js";
import { decodeQrImage } from "../packages/qr-core/src/index.js";
import { renderPublishedMembershipStampSvg } from "../packages/stamp-engine/src/index.js";
import {
  type ComposedWalletArtwork,
  composeWalletArtwork,
  type WalletArtworkTarget,
  walletArtworkInputFromStampRender,
} from "../packages/wallet-artwork/src/index.js";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = resolve(repositoryRoot, "artifacts/wallet-preview-mobile-calibration");

interface Crop {
  readonly left: number;
  readonly top: number;
  readonly width: number;
  readonly height: number;
}

interface Rect {
  readonly left: number;
  readonly top: number;
  readonly width: number;
  readonly height: number;
}

interface MeasuredGeometry {
  readonly referenceScale: { readonly x: number; readonly y: number };
  readonly cardCornerRadius: number;
  readonly elements: Readonly<Record<string, Rect>>;
  readonly textAntialiasRegions: readonly Rect[];
  readonly qrRegion: Rect | undefined;
  /**
   * Areas not generated by the production compositor. These are allowed only
   * in the Poster artwork-only comparison, where Apple overlays material and
   * the primary logo on top of the production Poster pixels.
   */
  readonly artworkOnlyExcludedRegions?: readonly Rect[];
}

interface QrGeometryMeasurement {
  /** The red/accent plate boundary, not the QR modules. */
  readonly plateBounds: Rect | undefined;
  /** The black/white QR code-module square, excluding the outer quiet zone. */
  readonly dataBounds: Rect | undefined;
  /** Plate-to-module inset in reference pixels. */
  readonly quietZone:
    | {
        readonly left: number;
        readonly top: number;
        readonly right: number;
        readonly bottom: number;
      }
    | undefined;
  readonly center: { readonly x: number; readonly y: number } | undefined;
  /** Corner radius inferred from the accent outline's left edge. */
  readonly estimatedRadius: number | undefined;
}

interface QrComparisonMeasurement {
  readonly reference: QrGeometryMeasurement;
  readonly production: QrGeometryMeasurement;
  /** Audit boundary for the sole QR exclusion: code modules only. */
  readonly maskedModuleBounds: Rect | undefined;
}

interface ArtworkRegistration {
  /** Uniform source-to-reference scale; non-uniform fitting is never used here. */
  readonly scale: number;
  /** Subpixel translation in reference-artwork coordinates. */
  readonly translateX: number;
  readonly translateY: number;
  /** Independently measured axis scales, retained to expose capture anisotropy. */
  readonly axisScale: { readonly x: number; readonly y: number };
  readonly anisotropy: number;
}

interface Fixture {
  readonly id: "google" | "apple-ios27" | "apple-legacy";
  readonly referenceCrop: Crop;
  /** The exact full-compositor region registered inside the golden card crop. */
  readonly referenceArtworkCrop: Crop;
  readonly previewCrop: Crop;
  readonly profile: "GOOGLE_WALLET" | "APPLE_WALLET";
  readonly appleWalletVariant?: "LEGACY" | "POSTER";
  readonly target: WalletArtworkTarget;
  readonly locale: "en" | "ar";
  readonly organizationName: string;
  readonly programName: string;
  readonly memberName: string;
  readonly rewardSummary: string;
  readonly progress: number;
  readonly goal: number;
  readonly colors: {
    readonly background: string;
    readonly foreground: string;
    readonly accent: string;
    readonly secondary: string;
  };
  readonly stampSize: number;
  readonly filledArtwork: string;
  readonly emptyArtwork: string;
}

const circleArtwork = (filled: boolean) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" fill="${filled ? "#E4572E" : "#F7F4EE"}"${filled ? "" : ' stroke="#241916" stroke-width="7"'}/></svg>`;

function required<T>(value: T | undefined, label: string): T {
  if (value === undefined) throw new Error(`${label} is required.`);
  return value;
}

const heritage = required(findProgramTemplate("BARBERSHOP_HERITAGE"), "Heritage template");
const coffee = required(findProgramTemplate("COFFEE"), "Coffee template");
const heritageArtwork = resolveProductionTemplateStampArtwork(heritage);
const coffeeArtwork = resolveProductionTemplateStampArtwork(coffee);

const fixtures: readonly Fixture[] = [
  {
    id: "google",
    // Actual Android Wallet card only. Status/navigation chrome is deliberately excluded.
    referenceCrop: { left: 54, top: 249, width: 814, height: 1035 },
    referenceArtworkCrop: { left: 3, top: 395, width: 808, height: 636 },
    previewCrop: { left: 24, top: 20, width: 412, height: 524 },
    profile: "GOOGLE_WALLET",
    target: "GOOGLE_HERO",
    locale: "en",
    organizationName: "Hamza Cafe",
    programName: "Heritage Barber rewards",
    memberName: "Alhamzah Abed",
    rewardSummary: "A classic grooming service",
    progress: 0,
    goal: 8,
    colors: {
      background: heritage.colors.background,
      foreground: heritage.colors.foreground,
      accent: heritage.colors.accent,
      secondary: heritage.colors.secondary,
    },
    stampSize: heritage.layout.stampSize,
    filledArtwork: heritageArtwork.filled.content,
    emptyArtwork: heritageArtwork.empty.content,
  },
  {
    id: "apple-ios27",
    // The full Poster Generic face, including its empty native continuation.
    referenceCrop: { left: 47, top: 300, width: 848, height: 1166 },
    referenceArtworkCrop: { left: 0, top: 52, width: 848, height: 1062 },
    previewCrop: { left: 51, top: 20, width: 358, height: 492 },
    profile: "APPLE_WALLET",
    appleWalletVariant: "POSTER",
    target: "APPLE_POSTER",
    locale: "ar",
    organizationName: "WAFLO",
    programName: "بطاقة الوفاء / Cedar Circle",
    memberName: "Sara / سارة",
    rewardSummary: "هدية مجانية / Complimentary reward",
    progress: 5,
    goal: 8,
    colors: {
      background: "#F7F4EE",
      foreground: "#241916",
      accent: "#E4572E",
      secondary: "#F3A712",
    },
    stampSize: 48,
    filledArtwork: circleArtwork(true),
    emptyArtwork: circleArtwork(false),
  },
  {
    id: "apple-legacy",
    // Actual legacy pass only. The add-sheet, status bar, and Wallet title are excluded.
    referenceCrop: { left: 35, top: 435, width: 874, height: 1232 },
    referenceArtworkCrop: { left: 0, top: 142, width: 874, height: 336 },
    previewCrop: { left: 24, top: 20, width: 412, height: 581 },
    profile: "APPLE_WALLET",
    appleWalletVariant: "LEGACY",
    target: "APPLE_LEGACY_STRIP",
    locale: "en",
    organizationName: "Waflo Roastery",
    programName: "Coffee",
    memberName: "Preview member",
    rewardSummary: "A coffee on us",
    progress: 5,
    goal: 8,
    colors: {
      background: coffee.colors.background,
      foreground: coffee.colors.foreground,
      accent: coffee.colors.accent,
      secondary: coffee.colors.secondary,
    },
    stampSize: coffee.layout.stampSize,
    filledArtwork: coffeeArtwork.filled.content,
    emptyArtwork: coffeeArtwork.empty.content,
  },
];

function digest(value: string) {
  return createHash("sha256").update(value).digest("hex");
}

async function composeFixture(fixture: Fixture) {
  const renderedStamp = renderPublishedMembershipStampSvg({
    organizationId: "00000000-0000-4000-8000-000000000001",
    programId: "00000000-0000-4000-8000-000000000002",
    programVersionId: "00000000-0000-4000-8000-000000000003",
    membershipId: "00000000-0000-4000-8000-000000000004",
    rendererSchemaVersion: "waflo-stamp-render-v1",
    locale: fixture.locale,
    requiredStampCount: fixture.goal,
    currentStampCount: fixture.progress,
    rewardReady: fixture.progress >= fixture.goal,
    layoutType: "GRID",
    layoutConfiguration: { columns: 4 },
    visualTheme: {
      filledColor: fixture.colors.accent,
      emptyColor: fixture.colors.secondary,
      accentColor: fixture.colors.accent,
      backgroundColor: fixture.colors.background,
      foregroundColor: fixture.colors.foreground,
      stampSize: fixture.stampSize,
      spacing: 8,
    },
    filledArtwork: { kind: "svg", content: fixture.filledArtwork, trusted: true },
    emptyArtwork: { kind: "svg", content: fixture.emptyArtwork, trusted: true },
    assetDigests: {
      filled: digest(fixture.filledArtwork),
      empty: digest(fixture.emptyArtwork),
    },
    outputProfile: fixture.profile,
  });
  const artwork = await composeWalletArtwork(
    walletArtworkInputFromStampRender(
      {
        organizationName: fixture.organizationName,
        programName: fixture.programName,
        memberName: fixture.memberName,
        credentialPayload: "waflo-wallet-preview-only",
        rewardLabel: fixture.rewardSummary,
        stampRenderInput: {
          layoutType: "GRID",
          locale: fixture.locale,
          currentStampCount: fixture.progress,
          requiredStampCount: fixture.goal,
          rewardReady: fixture.progress >= fixture.goal,
          visualTheme: {
            backgroundColor: fixture.colors.background,
            foregroundColor: fixture.colors.foreground,
            accentColor: fixture.colors.accent,
            emptyColor: fixture.colors.secondary,
            stampSize: fixture.stampSize,
          },
        },
      },
      renderedStamp,
    ),
    fixture.target,
  );
  const walletArtwork = {
    target: artwork.target,
    dataUri: `data:image/png;base64,${artwork.bytes.toString("base64")}`,
    width: artwork.width,
    height: artwork.height,
  } as const;
  const preview = composeProgramPreview({
    profile: fixture.profile,
    locale: fixture.locale,
    organizationName: fixture.organizationName,
    programName: fixture.programName,
    shortDescription: "Reference fixture only.",
    rewardSummary: fixture.rewardSummary,
    terms: "Reference fixture only.",
    progress: fixture.progress,
    goal: fixture.goal,
    stampSvg: renderedStamp.svg,
    stampLayout: "GRID",
    ...(fixture.appleWalletVariant ? { appleWalletVariant: fixture.appleWalletVariant } : {}),
    backgroundColor: fixture.colors.background,
    foregroundColor: fixture.colors.foreground,
    accentColor: fixture.colors.accent,
    secondaryColor: fixture.colors.secondary,
    walletArtwork,
    customerWebVariant: "CARD",
    apple: {
      headerLabel: "STAMPS",
      headerValue: `${fixture.progress}/${fixture.goal}`,
      secondaryLabel: "REWARD",
      barcodeLabel: "QR",
      showBackContent: true,
    },
    google: {
      title: fixture.programName,
      subtitle: "Reference fixture only.",
      detailsLabel: "STAMPS",
      barcodeLabel: "QR",
    },
  });
  return { artwork, preview };
}

async function rawImage(input: Buffer) {
  return sharp(input)
    .rotate()
    .toColourspace("srgb")
    .flatten({ background: "#FFFFFF" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
}

/**
 * Mobile screenshots and Sharp-generated SVGs arrive through different image
 * paths. Normalize both deterministically before any registration or score:
 * orientation applied, embedded profile converted to sRGB, alpha flattened
 * onto the same white canvas, and lossless PNG output. No blur or color
 * threshold is used to improve a score.
 */
async function normalizedPng(input: Buffer): Promise<Buffer> {
  return sharp(input)
    .rotate()
    .toColourspace("srgb")
    .flatten({ background: "#FFFFFF" })
    .ensureAlpha()
    .png({ compressionLevel: 9, adaptiveFiltering: true })
    .toBuffer();
}

function uniformRegistrationSeed(
  reference: Crop,
  source: { readonly width: number; readonly height: number },
): ArtworkRegistration {
  const axisScale = {
    x: reference.width / source.width,
    y: reference.height / source.height,
  };
  const scale = (axisScale.x + axisScale.y) / 2;
  return {
    scale,
    translateX: (reference.width - source.width * scale) / 2,
    translateY: (reference.height - source.height * scale) / 2,
    axisScale,
    anisotropy: Math.abs(axisScale.x - axisScale.y) / scale,
  };
}

/**
 * Rasterizes an artwork candidate using a single affine scale and translation.
 * The SVG viewBox keeps fractional translation intact; there is deliberately no
 * per-axis resize, rotation, perspective, or other compensating warp.
 */
async function renderRegisteredArtwork(
  artwork: ComposedWalletArtwork,
  fixture: Fixture,
  registration: ArtworkRegistration,
  maximumDimension = 0,
): Promise<Buffer> {
  const source = (await normalizedPng(Buffer.from(artwork.bytes))).toString("base64");
  const reference = fixture.referenceArtworkCrop;
  const outputScale =
    maximumDimension > 0
      ? Math.min(1, maximumDimension / Math.max(reference.width, reference.height))
      : 1;
  const width = Math.max(1, Math.round(reference.width * outputScale));
  const height = Math.max(1, Math.round(reference.height * outputScale));
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${reference.width} ${reference.height}"><rect width="${reference.width}" height="${reference.height}" fill="${fixture.colors.background}"/><image href="data:image/png;base64,${source}" width="${artwork.width}" height="${artwork.height}" transform="translate(${registration.translateX} ${registration.translateY}) scale(${registration.scale})"/></svg>`;
  return normalizedPng(Buffer.from(svg, "utf8"));
}

/** Applies the same allowed uniform registration to a rasterized dashboard card. */
async function renderRegisteredPreviewCard(
  card: Buffer,
  fixture: Fixture,
  registration: ArtworkRegistration,
  maximumDimension = 0,
): Promise<Buffer> {
  const source = await rawImage(card);
  const reference = fixture.referenceCrop;
  const outputScale =
    maximumDimension > 0
      ? Math.min(1, maximumDimension / Math.max(reference.width, reference.height))
      : 1;
  const width = Math.max(1, Math.round(reference.width * outputScale));
  const height = Math.max(1, Math.round(reference.height * outputScale));
  const dataUri = (await normalizedPng(card)).toString("base64");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${reference.width} ${reference.height}"><image href="data:image/png;base64,${dataUri}" width="${source.info.width}" height="${source.info.height}" transform="translate(${registration.translateX} ${registration.translateY}) scale(${registration.scale})"/></svg>`;
  return normalizedPng(Buffer.from(svg, "utf8"));
}

async function quickSimilarity(reference: Buffer, preview: Buffer): Promise<number> {
  const [referenceRaw, previewRaw] = await Promise.all([rawImage(reference), rawImage(preview)]);
  if (
    referenceRaw.info.width !== previewRaw.info.width ||
    referenceRaw.info.height !== previewRaw.info.height
  ) {
    throw new Error("Registration candidates must share comparison dimensions.");
  }
  let difference = 0;
  for (let index = 0; index < referenceRaw.data.length; index += 4) {
    difference +=
      Math.abs(referenceRaw.data[index] - previewRaw.data[index]) +
      Math.abs(referenceRaw.data[index + 1] - previewRaw.data[index + 1]) +
      Math.abs(referenceRaw.data[index + 2] - previewRaw.data[index + 2]);
  }
  return 1 - difference / (referenceRaw.info.width * referenceRaw.info.height * 3 * 255);
}

/**
 * Finds the best permitted capture registration around the measured art slot.
 * The coarse and fine grids are intentionally small: their job is to expose
 * DPR/raster offset, never to conceal a real layout error.
 */
async function estimateArtworkRegistration(
  reference: Buffer,
  artwork: ComposedWalletArtwork,
  fixture: Fixture,
): Promise<ArtworkRegistration> {
  const seed = uniformRegistrationSeed(fixture.referenceArtworkCrop, artwork);
  const referenceSmall = await sharp(reference)
    .resize({ width: 240, height: 240, fit: "inside", kernel: sharp.kernel.lanczos3 })
    .png()
    .toBuffer();
  let best = seed;
  let bestSimilarity = -Infinity;
  const search = async (
    scaleOffsets: readonly number[],
    translations: readonly number[],
    base: ArtworkRegistration,
  ) => {
    for (const scaleOffset of scaleOffsets) {
      for (const translateXOffset of translations) {
        for (const translateYOffset of translations) {
          const candidate: ArtworkRegistration = {
            ...base,
            scale: base.scale + scaleOffset,
            translateX: base.translateX + translateXOffset,
            translateY: base.translateY + translateYOffset,
          };
          const rendered = await renderRegisteredArtwork(artwork, fixture, candidate, 240);
          const score = await quickSimilarity(referenceSmall, rendered);
          if (score > bestSimilarity) {
            best = candidate;
            bestSimilarity = score;
          }
        }
      }
    }
  };
  await search([-0.003, -0.002, -0.001, 0, 0.001, 0.002, 0.003], [-1, -0.5, 0, 0.5, 1], seed);
  const coarseBest = best;
  bestSimilarity = -Infinity;
  await search([-0.0008, -0.0004, 0, 0.0004, 0.0008], [-0.5, -0.25, 0, 0.25, 0.5], coarseBest);
  return best;
}

/**
 * The dashboard card is registered with the identical constrained model as
 * artwork: one scale plus a subpixel translation. Its nearly equal measured
 * axes are retained as capture diagnostics, never applied independently.
 */
async function estimatePreviewRegistration(
  reference: Buffer,
  card: Buffer,
  fixture: Fixture,
): Promise<ArtworkRegistration> {
  const cardRaw = await rawImage(card);
  const seed = uniformRegistrationSeed(fixture.referenceCrop, {
    width: cardRaw.info.width,
    height: cardRaw.info.height,
  });
  const referenceSmall = await sharp(reference)
    .resize({ width: 240, height: 240, fit: "inside", kernel: sharp.kernel.lanczos3 })
    .png()
    .toBuffer();
  let best = seed;
  let bestSimilarity = -Infinity;
  const search = async (
    scaleOffsets: readonly number[],
    translations: readonly number[],
    base: ArtworkRegistration,
  ) => {
    for (const scaleOffset of scaleOffsets) {
      for (const translateXOffset of translations) {
        for (const translateYOffset of translations) {
          const candidate: ArtworkRegistration = {
            ...base,
            scale: base.scale + scaleOffset,
            translateX: base.translateX + translateXOffset,
            translateY: base.translateY + translateYOffset,
          };
          const rendered = await renderRegisteredPreviewCard(card, fixture, candidate, 240);
          const score = await quickSimilarity(referenceSmall, rendered);
          if (score > bestSimilarity) {
            best = candidate;
            bestSimilarity = score;
          }
        }
      }
    }
  };
  await search([-0.003, -0.002, -0.001, 0, 0.001, 0.002, 0.003], [-1, -0.5, 0, 0.5, 1], seed);
  const coarseBest = best;
  bestSimilarity = -Infinity;
  await search([-0.0008, -0.0004, 0, 0.0004, 0.0008], [-0.5, -0.25, 0, 0.25, 0.5], coarseBest);
  return best;
}

function mapPreviewRectToReference(
  fixture: Fixture,
  rect: Rect,
  registration: ArtworkRegistration,
): Rect {
  return {
    left: (rect.left - fixture.previewCrop.left) * registration.scale + registration.translateX,
    top: (rect.top - fixture.previewCrop.top) * registration.scale + registration.translateY,
    width: rect.width * registration.scale,
    height: rect.height * registration.scale,
  };
}

function geometryForFixture(
  fixture: Fixture,
  artwork: ComposedWalletArtwork,
  registration: ArtworkRegistration,
): MeasuredGeometry {
  const map = (rect: Rect) => mapPreviewRectToReference(fixture, rect, registration);
  const elements: Record<string, Rect> = {
    outerCard: map(fixture.previewCrop),
  };
  const textAntialiasRegions: Rect[] = [];
  let cardCornerRadius = 0;
  let qrRegion: Rect | undefined;

  if (fixture.id === "google") {
    cardCornerRadius = 32 * registration.scale;
    Object.assign(elements, {
      merchantLogo: map({ left: 48, top: 45, width: 34, height: 34 }),
      merchantName: map({ left: 96, top: 49, width: 260, height: 23 }),
      divider: map({ left: 48, top: 97, width: 364, height: 2 }),
      programTitle: map({ left: 42, top: 110, width: 360, height: 72 }),
      fullProductionArtwork: map({ left: 25.5, top: 220, width: 409, height: 321.7286821705426 }),
    });
    textAntialiasRegions.push(elements.merchantName, elements.programTitle);
    if (artwork.qrRegion) {
      qrRegion = map({
        left: 25.5 + (artwork.qrRegion.left / artwork.width) * 409,
        top: 220 + (artwork.qrRegion.top / artwork.height) * 321.7286821705426,
        width: (artwork.qrRegion.width / artwork.width) * 409,
        height: (artwork.qrRegion.height / artwork.height) * 321.7286821705426,
      });
    }
  } else if (fixture.id === "apple-ios27") {
    cardCornerRadius = 14 * registration.scale;
    Object.assign(elements, {
      merchantLogo: map({ left: 64, top: 38, width: 29, height: 29 }),
      merchantName: map({ left: 102, top: 41, width: 180, height: 22 }),
      fullProductionArtwork: map({ left: 51, top: 42, width: 358, height: 448 }),
      nativeReserve: map({ left: 51, top: 490, width: 358, height: 22 }),
    });
    textAntialiasRegions.push(elements.merchantName);
    if (artwork.qrRegion) {
      qrRegion = map({
        left: 51 + (artwork.qrRegion.left / artwork.width) * 358,
        top: 42 + (artwork.qrRegion.top / artwork.height) * 448,
        width: (artwork.qrRegion.width / artwork.width) * 358,
        height: (artwork.qrRegion.height / artwork.height) * 448,
      });
    }
  } else {
    cardCornerRadius = 16 * registration.scale;
    Object.assign(elements, {
      merchantLogo: map({ left: 38, top: 31, width: 40, height: 40 }),
      merchantName: map({ left: 86, top: 39, width: 235, height: 24 }),
      stampsHeader: map({ left: 332, top: 29, width: 72, height: 38 }),
      fullProductionArtwork: map({ left: 24, top: 87, width: 412, height: 158.41509433962264 }),
      rewardField: map({ left: 48, top: 250, width: 300, height: 58 }),
      nativeQrFrame: map({ left: 151, top: 425, width: 159, height: 159 }),
      nativeEmptyReserve: map({ left: 24, top: 308, width: 412, height: 117 }),
    });
    textAntialiasRegions.push(elements.merchantName, elements.stampsHeader, elements.rewardField);
    qrRegion = elements.nativeQrFrame;
  }

  return {
    referenceScale: {
      x: registration.axisScale.x,
      y: registration.axisScale.y,
    },
    cardCornerRadius,
    elements,
    textAntialiasRegions,
    qrRegion,
  };
}

function artworkGeometryForFixture(
  fixture: Fixture,
  artwork: ComposedWalletArtwork,
  registration: ArtworkRegistration,
): MeasuredGeometry {
  const scaleX = registration.scale;
  const scaleY = registration.scale;
  const map = (rect: Rect): Rect => ({
    left: rect.left * scaleX + registration.translateX,
    top: rect.top * scaleY + registration.translateY,
    width: rect.width * scaleX,
    height: rect.height * scaleY,
  });
  const elements: Record<string, Rect> = {
    fullProductionArtwork: {
      left: 0,
      top: 0,
      width: fixture.referenceArtworkCrop.width,
      height: fixture.referenceArtworkCrop.height,
    },
    stampPanel: map(artwork.stampPanelRegion),
    stampGrid: map(artwork.stampPlacement),
  };
  // Production artwork text belongs to the compositor and remains fully
  // scored. Native system-font AA is masked only in the dashboard card model.
  const textAntialiasRegions: Rect[] = [];
  const qrRegion = artwork.qrRegion ? map(artwork.qrRegion) : undefined;
  if (artwork.identityRegion) elements.identity = map(artwork.identityRegion);
  if (artwork.counterBadgeRegion) elements.counter = map(artwork.counterBadgeRegion);
  if (artwork.rewardRegion) elements.reward = map(artwork.rewardRegion);
  if (qrRegion) elements.qrFrame = qrRegion;
  const artworkOnlyExcludedRegions =
    fixture.id === "apple-ios27"
      ? [
          // The preview’s native material spans card y=20–161 while the
          // production Poster starts at y=42. This exact overlap is owned by
          // Apple, including its primary-logo rendering; it cannot fairly
          // score the compositor itself. The lower reserve begins after this
          // artwork crop, so it is intentionally not padded into this mask.
          {
            left: 0,
            top: 0,
            width: fixture.referenceArtworkCrop.width,
            height: Math.min(
              fixture.referenceArtworkCrop.height,
              (161 - 42) * (fixture.referenceCrop.height / fixture.previewCrop.height),
            ),
          },
        ]
      : undefined;
  return {
    referenceScale: registration.axisScale,
    cardCornerRadius: 0,
    elements,
    textAntialiasRegions,
    qrRegion,
    ...(artworkOnlyExcludedRegions ? { artworkOnlyExcludedRegions } : {}),
  };
}

function pointIsInside(rect: Rect | undefined, x: number, y: number): boolean {
  return (
    rect !== undefined &&
    x >= rect.left &&
    x < rect.left + rect.width &&
    y >= rect.top &&
    y < rect.top + rect.height
  );
}

function luminance(data: Buffer, index: number): number {
  return data[index] * 0.2126 + data[index + 1] * 0.7152 + data[index + 2] * 0.0722;
}

function hasEdgeContrast(data: Buffer, index: number, width: number, height: number): boolean {
  const pixel = Math.floor(index / 4);
  const x = pixel % width;
  const y = Math.floor(pixel / width);
  const base = luminance(data, index);
  const neighbors: number[] = [];
  if (x > 0) neighbors.push(index - 4);
  if (x + 1 < width) neighbors.push(index + 4);
  if (y > 0) neighbors.push(index - width * 4);
  if (y + 1 < height) neighbors.push(index + width * 4);
  return neighbors.some((neighbor) => Math.abs(luminance(data, neighbor) - base) >= 14);
}

function isNativeTextAntialiasPixel(
  reference: Buffer,
  preview: Buffer,
  index: number,
  width: number,
  height: number,
  textRegions: readonly Rect[],
): boolean {
  const pixel = Math.floor(index / 4);
  const x = pixel % width;
  const y = Math.floor(pixel / width);
  if (!textRegions.some((region) => pointIsInside(region, x, y))) return false;
  const referenceLuminance = luminance(reference, index);
  const previewLuminance = luminance(preview, index);
  const referenceEdge = hasEdgeContrast(reference, index, width, height);
  const previewEdge = hasEdgeContrast(preview, index, width, height);
  // Native system fonts are captured after a different rasterizer/DPR pass.
  // Mask only the contour pixels: solid interiors, geometry, and whitespace
  // remain scored. One image can legitimately have the antialiased contour a
  // fraction of a pixel to either side of the other, so requiring both pixels
  // to be dark would incorrectly count that unavoidable capture difference.
  return (
    (referenceEdge || previewEdge) &&
    Math.min(referenceLuminance, previewLuminance) < 220 &&
    Math.max(referenceLuminance, previewLuminance) > 32
  );
}

function boundedRect(rect: Rect, width: number, height: number): Rect {
  const left = Math.max(0, Math.floor(rect.left));
  const top = Math.max(0, Math.floor(rect.top));
  const right = Math.min(width, Math.ceil(rect.left + rect.width));
  const bottom = Math.min(height, Math.ceil(rect.top + rect.height));
  return { left, top, width: Math.max(0, right - left), height: Math.max(0, bottom - top) };
}

function boundsFromPixels(
  _data: Buffer,
  width: number,
  height: number,
  search: Rect,
  matches: (index: number) => boolean,
): Rect | undefined {
  const bounded = boundedRect(search, width, height);
  let left = width;
  let top = height;
  let right = -1;
  let bottom = -1;
  for (let y = bounded.top; y < bounded.top + bounded.height; y += 1) {
    for (let x = bounded.left; x < bounded.left + bounded.width; x += 1) {
      const index = (y * width + x) * 4;
      if (!matches(index)) continue;
      left = Math.min(left, x);
      top = Math.min(top, y);
      right = Math.max(right, x);
      bottom = Math.max(bottom, y);
    }
  }
  return right < left || bottom < top
    ? undefined
    : { left, top, width: right - left + 1, height: bottom - top + 1 };
}

function estimatedQrCornerRadius(
  data: Buffer,
  width: number,
  plate: Rect | undefined,
): number | undefined {
  if (!plate) return undefined;
  const bounded = boundedRect(plate, width, data.length / (width * 4));
  const candidates: number[] = [];
  for (let x = bounded.left; x < Math.min(bounded.left + 4, bounded.left + bounded.width); x += 1) {
    for (let y = bounded.top; y < bounded.top + bounded.height; y += 1) {
      const index = (y * width + x) * 4;
      const redAccent =
        data[index] >= data[index + 1] + 12 &&
        data[index] >= data[index + 2] + 12 &&
        luminance(data, index) > 52 &&
        luminance(data, index) < 235;
      if (redAccent) {
        candidates.push(y - bounded.top);
        break;
      }
    }
  }
  return candidates.length === 0
    ? undefined
    : Number(
        (candidates.reduce((total, value) => total + value, 0) / candidates.length).toFixed(2),
      );
}

/**
 * Reads QR geometry from the rendered pixels without using its content. Accent
 * pixels locate the outer plate; dark pixels are searched only within the
 * plate interior, so the frame itself cannot be classified as a module.
 */
function measureQrGeometry(
  data: Buffer,
  width: number,
  height: number,
  expectedFrame: Rect | undefined,
): QrGeometryMeasurement {
  if (!expectedFrame) {
    return {
      plateBounds: undefined,
      dataBounds: undefined,
      quietZone: undefined,
      center: undefined,
      estimatedRadius: undefined,
    };
  }
  const frameSearch = {
    left: expectedFrame.left - 12,
    top: expectedFrame.top - 12,
    width: expectedFrame.width + 24,
    height: expectedFrame.height + 24,
  };
  const plateBounds = boundsFromPixels(data, width, height, frameSearch, (index) => {
    const red = data[index] ?? 0;
    const green = data[index + 1] ?? 0;
    const blue = data[index + 2] ?? 0;
    const lightness = luminance(data, index);
    return red >= green + 12 && red >= blue + 12 && lightness > 52 && lightness < 235;
  });
  const plate = plateBounds ?? expectedFrame;
  const dataSearch = {
    left: plate.left + Math.max(5, plate.width * 0.07),
    top: plate.top + Math.max(5, plate.height * 0.07),
    width: plate.width - Math.max(10, plate.width * 0.14),
    height: plate.height - Math.max(10, plate.height * 0.14),
  };
  const dataBounds = boundsFromPixels(data, width, height, dataSearch, (index) => {
    // QR module ink is the only nearly neutral, dark content inside this
    // inner field. The accent outline lies outside dataSearch.
    const red = data[index] ?? 0;
    const green = data[index + 1] ?? 0;
    const blue = data[index + 2] ?? 0;
    return (
      luminance(data, index) < 105 && Math.max(red, green, blue) - Math.min(red, green, blue) < 32
    );
  });
  const quietZone =
    dataBounds === undefined
      ? undefined
      : {
          left: Number((dataBounds.left - plate.left).toFixed(2)),
          top: Number((dataBounds.top - plate.top).toFixed(2)),
          right: Number(
            (plate.left + plate.width - (dataBounds.left + dataBounds.width)).toFixed(2),
          ),
          bottom: Number(
            (plate.top + plate.height - (dataBounds.top + dataBounds.height)).toFixed(2),
          ),
        };
  return {
    plateBounds,
    dataBounds,
    quietZone,
    center: {
      x: Number((plate.left + plate.width / 2).toFixed(2)),
      y: Number((plate.top + plate.height / 2).toFixed(2)),
    },
    estimatedRadius: estimatedQrCornerRadius(data, width, plateBounds),
  };
}

function measureQrComparison(
  reference: Buffer,
  preview: Buffer,
  width: number,
  height: number,
  expectedFrame: Rect | undefined,
): QrComparisonMeasurement | undefined {
  if (!expectedFrame) return undefined;
  const referenceGeometry = measureQrGeometry(reference, width, height, expectedFrame);
  const productionGeometry = measureQrGeometry(preview, width, height, expectedFrame);
  const dataBounds = [referenceGeometry.dataBounds, productionGeometry.dataBounds].filter(
    (bounds): bounds is Rect => bounds !== undefined,
  );
  const maskedModuleBounds =
    dataBounds.length === 0
      ? undefined
      : {
          left: Math.min(...dataBounds.map((bounds) => bounds.left)),
          top: Math.min(...dataBounds.map((bounds) => bounds.top)),
          width:
            Math.max(...dataBounds.map((bounds) => bounds.left + bounds.width)) -
            Math.min(...dataBounds.map((bounds) => bounds.left)),
          height:
            Math.max(...dataBounds.map((bounds) => bounds.top + bounds.height)) -
            Math.min(...dataBounds.map((bounds) => bounds.top)),
        };
  return {
    reference: referenceGeometry,
    production: productionGeometry,
    // The union covers only code-module pixels. Its one-pixel extent can
    // differ between captures after resampling; plate, quiet zone, and frame
    // remain outside this bounded audited exclusion.
    maskedModuleBounds,
  };
}

function qrModuleMask(qrDataRegion: Rect | undefined, index: number, width: number): boolean {
  const pixel = Math.floor(index / 4);
  const x = pixel % width;
  const y = Math.floor(pixel / width);
  return pointIsInside(qrDataRegion, x, y);
}

function regionSimilarity(reference: Buffer, preview: Buffer, width: number, region: Rect): number {
  const startX = Math.max(0, Math.floor(region.left));
  const endX = Math.min(width, Math.ceil(region.left + region.width));
  const height = reference.length / (width * 4);
  const startY = Math.max(0, Math.floor(region.top));
  const endY = Math.min(height, Math.ceil(region.top + region.height));
  let difference = 0;
  let pixels = 0;
  for (let y = startY; y < endY; y += 1) {
    for (let x = startX; x < endX; x += 1) {
      const index = (y * width + x) * 4;
      difference +=
        Math.abs(reference[index] - preview[index]) +
        Math.abs(reference[index + 1] - preview[index + 1]) +
        Math.abs(reference[index + 2] - preview[index + 2]);
      pixels += 1;
    }
  }
  return pixels === 0 ? 1 : 1 - difference / (pixels * 3 * 255);
}

function regionalErrorBreakdown(
  reference: Buffer,
  preview: Buffer,
  width: number,
  height: number,
  elements: Readonly<Record<string, Rect>>,
): readonly { readonly name: string; readonly rawErrorContribution: number }[] {
  // Specific content wins over its containing surface so these values are an
  // additive partition, not a misleading set of overlapping similarities.
  const priority = [
    "merchantLogo",
    "merchantName",
    "divider",
    "programTitle",
    "identity",
    "counter",
    "stampsHeader",
    "rewardField",
    "nativeQrFrame",
    "qrFrame",
    "reward",
    "stampGrid",
    "stampPanel",
  ];
  const regions = priority.flatMap((name) => {
    const region = elements[name];
    return region ? [{ name, region }] : [];
  });
  const differences = new Map<string, number>();
  let total = 0;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const index = (y * width + x) * 4;
      const difference =
        Math.abs(reference[index] - preview[index]) +
        Math.abs(reference[index + 1] - preview[index + 1]) +
        Math.abs(reference[index + 2] - preview[index + 2]);
      total += difference;
      const owner =
        regions.find(({ region }) => pointIsInside(region, x, y))?.name ?? "decorationsBackground";
      differences.set(owner, (differences.get(owner) ?? 0) + difference);
    }
  }
  return [...differences.entries()]
    .map(([name, difference]) => ({
      name,
      rawErrorContribution: total === 0 ? 0 : Number((difference / total).toFixed(6)),
    }))
    .sort((left, right) => right.rawErrorContribution - left.rawErrorContribution);
}

function isRectBorderPixel(region: Rect, x: number, y: number, thickness: number): boolean {
  return (
    x < region.left + thickness ||
    x >= region.left + region.width - thickness ||
    y < region.top + thickness ||
    y >= region.top + region.height - thickness
  );
}

/**
 * Additive, scored-pixel partition used for the Google forensic report.
 * Modules are deliberately retained as a named category even though their
 * payload-dependent interiors are excluded from the structural denominator.
 */
function structuralErrorBreakdown(
  reference: Buffer,
  preview: Buffer,
  width: number,
  height: number,
  geometry: MeasuredGeometry,
  qr: QrComparisonMeasurement | undefined,
  mask: Uint8Array,
): readonly {
  readonly name: string;
  readonly structuralErrorContribution: number;
  readonly rawErrorContribution: number;
  readonly maskedPixels: number;
}[] {
  const categoryFor = (x: number, y: number): string => {
    const plate = qr?.production.plateBounds;
    const data = qr?.maskedModuleBounds;
    if (pointIsInside(data, x, y)) return "qrModules";
    if (pointIsInside(plate, x, y)) {
      return isRectBorderPixel(plate, x, y, 5) ? "qrFrameGeometry" : "qrQuietZone";
    }
    if (geometry.elements.programTitle && pointIsInside(geometry.elements.programTitle, x, y)) {
      return "dashboardNativeTitle";
    }
    if (
      ["merchantLogo", "merchantName", "divider"].some((name) =>
        pointIsInside(geometry.elements[name], x, y),
      )
    ) {
      return "outerProviderWrapper";
    }
    for (const [element, category] of [
      ["identity", "identity"],
      ["counter", "counter"],
      ["reward", "reward"],
      ["stampGrid", "stampGrid"],
      ["stampPanel", "stampPanel"],
    ] as const) {
      if (pointIsInside(geometry.elements[element], x, y)) return category;
    }
    if (
      geometry.elements.fullProductionArtwork &&
      !pointIsInside(geometry.elements.fullProductionArtwork, x, y)
    ) {
      return "outerProviderWrapper";
    }
    return "backgroundDecorations";
  };
  const raw = new Map<string, number>();
  const structural = new Map<string, number>();
  const masked = new Map<string, number>();
  let totalRaw = 0;
  let totalStructural = 0;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const pixel = y * width + x;
      const index = pixel * 4;
      const difference =
        Math.abs(reference[index] - preview[index]) +
        Math.abs(reference[index + 1] - preview[index + 1]) +
        Math.abs(reference[index + 2] - preview[index + 2]);
      const category = categoryFor(x, y);
      raw.set(category, (raw.get(category) ?? 0) + difference);
      totalRaw += difference;
      if (mask[pixel]) {
        masked.set(category, (masked.get(category) ?? 0) + 1);
      } else {
        structural.set(category, (structural.get(category) ?? 0) + difference);
        totalStructural += difference;
      }
    }
  }
  const names = new Set([...raw.keys(), ...structural.keys(), ...masked.keys()]);
  return [...names]
    .map((name) => ({
      name,
      rawErrorContribution:
        totalRaw === 0 ? 0 : Number(((raw.get(name) ?? 0) / totalRaw).toFixed(6)),
      structuralErrorContribution:
        totalStructural === 0
          ? 0
          : Number(((structural.get(name) ?? 0) / totalStructural).toFixed(6)),
      maskedPixels: masked.get(name) ?? 0,
    }))
    .sort((left, right) => right.structuralErrorContribution - left.structuralErrorContribution);
}

function structuralSsim(
  reference: Buffer,
  preview: Buffer,
  mask: Uint8Array,
  width: number,
  height: number,
): number {
  const c1 = (0.01 * 255) ** 2;
  const c2 = (0.03 * 255) ** 2;
  let total = 0;
  let blocks = 0;
  for (let top = 0; top < height; top += 8) {
    for (let left = 0; left < width; left += 8) {
      const samples: number[] = [];
      for (let y = top; y < Math.min(height, top + 8); y += 1) {
        for (let x = left; x < Math.min(width, left + 8); x += 1) {
          const pixel = y * width + x;
          if (!mask[pixel]) samples.push(pixel);
        }
      }
      if (samples.length < 4) continue;
      let referenceMean = 0;
      let previewMean = 0;
      for (const pixel of samples) {
        const index = pixel * 4;
        referenceMean += luminance(reference, index);
        previewMean += luminance(preview, index);
      }
      referenceMean /= samples.length;
      previewMean /= samples.length;
      let referenceVariance = 0;
      let previewVariance = 0;
      let covariance = 0;
      for (const pixel of samples) {
        const index = pixel * 4;
        const referenceDelta = luminance(reference, index) - referenceMean;
        const previewDelta = luminance(preview, index) - previewMean;
        referenceVariance += referenceDelta ** 2;
        previewVariance += previewDelta ** 2;
        covariance += referenceDelta * previewDelta;
      }
      const denominator = samples.length - 1;
      referenceVariance /= denominator;
      previewVariance /= denominator;
      covariance /= denominator;
      total +=
        ((2 * referenceMean * previewMean + c1) * (2 * covariance + c2)) /
        ((referenceMean ** 2 + previewMean ** 2 + c1) * (referenceVariance + previewVariance + c2));
      blocks += 1;
    }
  }
  return blocks === 0 ? 1 : total / blocks;
}

async function compare(reference: Buffer, preview: Buffer, geometry: MeasuredGeometry) {
  const [referenceRaw, previewRaw] = await Promise.all([rawImage(reference), rawImage(preview)]);
  if (
    referenceRaw.info.width !== previewRaw.info.width ||
    referenceRaw.info.height !== previewRaw.info.height
  ) {
    throw new Error("Reference and preview must have matching comparison dimensions.");
  }
  const diff = Buffer.alloc(referenceRaw.data.length);
  const maskedDiff = Buffer.alloc(referenceRaw.data.length);
  const maskVisualization = Buffer.alloc(referenceRaw.data.length);
  const mask = new Uint8Array(referenceRaw.info.width * referenceRaw.info.height);
  const qrMeasurement = measureQrComparison(
    referenceRaw.data,
    previewRaw.data,
    referenceRaw.info.width,
    referenceRaw.info.height,
    geometry.qrRegion,
  );
  let totalDifference = 0;
  let structuralDifference = 0;
  let structuralPixels = 0;
  const pixels = referenceRaw.info.width * referenceRaw.info.height;
  for (let index = 0; index < referenceRaw.data.length; index += 4) {
    const channelDifference =
      Math.abs(referenceRaw.data[index] - previewRaw.data[index]) +
      Math.abs(referenceRaw.data[index + 1] - previewRaw.data[index + 1]) +
      Math.abs(referenceRaw.data[index + 2] - previewRaw.data[index + 2]);
    totalDifference += channelDifference;
    const amplified = Math.min(255, Math.round(channelDifference * 1.6));
    diff[index] = amplified;
    diff[index + 1] = 0;
    diff[index + 2] = 0;
    diff[index + 3] = 255;
    const pixel = index / 4;
    const x = pixel % referenceRaw.info.width;
    const y = Math.floor(pixel / referenceRaw.info.width);
    const masked =
      geometry.artworkOnlyExcludedRegions?.some((region) => pointIsInside(region, x, y)) ||
      qrModuleMask(qrMeasurement?.maskedModuleBounds, index, referenceRaw.info.width) ||
      isNativeTextAntialiasPixel(
        referenceRaw.data,
        previewRaw.data,
        index,
        referenceRaw.info.width,
        referenceRaw.info.height,
        geometry.textAntialiasRegions,
      );
    if (masked) {
      mask[pixel] = 1;
      maskedDiff[index + 3] = 0;
      // Teal is a visible audit mask, never a hidden score adjustment.
      maskVisualization[index] = 0;
      maskVisualization[index + 1] = 174;
      maskVisualization[index + 2] = 190;
      maskVisualization[index + 3] = 255;
    } else {
      structuralDifference += channelDifference;
      structuralPixels += 1;
      maskedDiff[index] = amplified;
      maskedDiff[index + 1] = 0;
      maskedDiff[index + 2] = 0;
      maskedDiff[index + 3] = 255;
      maskVisualization[index] = 255;
      maskVisualization[index + 1] = 255;
      maskVisualization[index + 2] = 255;
      maskVisualization[index + 3] = 255;
    }
  }
  return {
    rawSimilarity: 1 - totalDifference / (pixels * 3 * 255),
    structuralPixelSimilarity:
      structuralPixels === 0 ? 1 : 1 - structuralDifference / (structuralPixels * 3 * 255),
    localStructuralSsim: structuralSsim(
      referenceRaw.data,
      previewRaw.data,
      mask,
      referenceRaw.info.width,
      referenceRaw.info.height,
    ),
    maskedPixels: pixels - structuralPixels,
    regionalErrorBreakdown: regionalErrorBreakdown(
      referenceRaw.data,
      previewRaw.data,
      referenceRaw.info.width,
      referenceRaw.info.height,
      geometry.elements,
    ),
    structuralErrorBreakdown: structuralErrorBreakdown(
      referenceRaw.data,
      previewRaw.data,
      referenceRaw.info.width,
      referenceRaw.info.height,
      geometry,
      qrMeasurement,
      mask,
    ),
    qrMeasurement,
    largestRawMismatchRegions: Object.entries(geometry.elements)
      .map(([name, region]) => ({
        name,
        rawSimilarity: regionSimilarity(
          referenceRaw.data,
          previewRaw.data,
          referenceRaw.info.width,
          region,
        ),
      }))
      .sort((left, right) => left.rawSimilarity - right.rawSimilarity)
      .map((region) => ({ ...region, rawSimilarity: Number(region.rawSimilarity.toFixed(6)) })),
    diff: await sharp(diff, {
      raw: { width: referenceRaw.info.width, height: referenceRaw.info.height, channels: 4 },
    })
      .png()
      .toBuffer(),
    maskedDiff: await sharp(maskedDiff, {
      raw: { width: referenceRaw.info.width, height: referenceRaw.info.height, channels: 4 },
    })
      .png()
      .toBuffer(),
    maskVisualization: await sharp(maskVisualization, {
      raw: { width: referenceRaw.info.width, height: referenceRaw.info.height, channels: 4 },
    })
      .png()
      .toBuffer(),
  };
}

async function runFixture(fixture: Fixture) {
  const { artwork, preview } = await composeFixture(fixture);
  const referencePath = resolve(outputDirectory, `${fixture.id}-reference-crop.png`);
  const [referenceCrop, previewPng, artworkReference, artworkPng] = await Promise.all([
    normalizedPng(await sharp(referencePath).png().toBuffer()),
    normalizedPng(await sharp(Buffer.from(preview.svg, "utf8")).png().toBuffer()),
    normalizedPng(
      await sharp(referencePath).extract(fixture.referenceArtworkCrop).png().toBuffer(),
    ),
    normalizedPng(Buffer.from(artwork.bytes)),
  ]);
  const previewCard = await normalizedPng(
    await sharp(previewPng).extract(fixture.previewCrop).png().toBuffer(),
  );
  const previewRegistration = await estimatePreviewRegistration(
    referenceCrop,
    previewCard,
    fixture,
  );
  const geometry = geometryForFixture(fixture, artwork, previewRegistration);
  const artworkRegistration = await estimateArtworkRegistration(artworkReference, artwork, fixture);
  const artworkGeometry = artworkGeometryForFixture(fixture, artwork, artworkRegistration);
  const [cardPreview, productionArtworkForComparison] = await Promise.all([
    renderRegisteredPreviewCard(previewCard, fixture, previewRegistration),
    renderRegisteredArtwork(artwork, fixture, artworkRegistration),
  ]);
  let decodedQrPayload: string | undefined;
  if (fixture.id === "google" && artwork.qrRegion) {
    const qrDataWidth = artwork.qrRegion.width - 14 * 2 + 5;
    const qr = await sharp(artwork.bytes)
      .extract({
        left: Math.round(artwork.qrRegion.left + 14),
        top: Math.round(artwork.qrRegion.top + 14),
        width: Math.round(qrDataWidth),
        height: Math.round(qrDataWidth),
      })
      .png()
      .toBuffer();
    decodedQrPayload = await decodeQrImage(qr, "image/png");
    if (decodedQrPayload !== "waflo-wallet-preview-only") {
      throw new Error("Google artwork QR did not decode to its exact fixture credential.");
    }
  }
  const [result, artworkResult] = await Promise.all([
    compare(referenceCrop, cardPreview, geometry),
    compare(artworkReference, productionArtworkForComparison, artworkGeometry),
  ]);
  await Promise.all([
    writeFile(resolve(outputDirectory, `${fixture.id}-reference-crop.png`), referenceCrop),
    writeFile(resolve(outputDirectory, `${fixture.id}-dashboard-preview.png`), cardPreview),
    writeFile(resolve(outputDirectory, `${fixture.id}-pixel-diff.png`), result.diff),
    writeFile(resolve(outputDirectory, `${fixture.id}-masked-pixel-diff.png`), result.maskedDiff),
    writeFile(
      resolve(outputDirectory, `${fixture.id}-structural-mask.png`),
      result.maskVisualization,
    ),
    writeFile(resolve(outputDirectory, `${fixture.id}-production-artwork.png`), artworkPng),
    writeFile(resolve(outputDirectory, `${fixture.id}-artwork-reference.png`), artworkReference),
    writeFile(
      resolve(outputDirectory, `${fixture.id}-artwork-current-production.png`),
      productionArtworkForComparison,
    ),
    writeFile(resolve(outputDirectory, `${fixture.id}-artwork-pixel-diff.png`), artworkResult.diff),
    writeFile(
      resolve(outputDirectory, `${fixture.id}-artwork-masked-pixel-diff.png`),
      artworkResult.maskedDiff,
    ),
    writeFile(
      resolve(outputDirectory, `${fixture.id}-artwork-structural-mask.png`),
      artworkResult.maskVisualization,
    ),
  ]);
  return {
    id: fixture.id,
    target: fixture.target,
    referenceCrop: fixture.referenceCrop,
    previewCrop: fixture.previewCrop,
    referenceAspectRatio: fixture.referenceCrop.width / fixture.referenceCrop.height,
    previewAspectRatio: fixture.previewCrop.width / fixture.previewCrop.height,
    geometry,
    dashboardRegistration: previewRegistration,
    rawSimilarity: Number(result.rawSimilarity.toFixed(6)),
    // This is the required structural score: the same pixel metric as raw,
    // with only QR modules and native text antialiasing excluded. Local SSIM
    // remains a diagnostic; it is not used to conceal geometry deltas.
    structuralSimilarity: Number(result.structuralPixelSimilarity.toFixed(6)),
    localStructuralSsim: Number(result.localStructuralSsim.toFixed(6)),
    structuralPixelSimilarity: Number(result.structuralPixelSimilarity.toFixed(6)),
    maskedPixels: result.maskedPixels,
    qrGeometry: result.qrMeasurement,
    structuralErrorBreakdown: result.structuralErrorBreakdown,
    largestRawMismatchRegions: result.largestRawMismatchRegions,
    regionalErrorBreakdown: result.regionalErrorBreakdown,
    artworkComparison: {
      referenceCrop: fixture.referenceArtworkCrop,
      registration: artworkRegistration,
      geometry: artworkGeometry,
      rawSimilarity: Number(artworkResult.rawSimilarity.toFixed(6)),
      structuralSimilarity: Number(artworkResult.structuralPixelSimilarity.toFixed(6)),
      localStructuralSsim: Number(artworkResult.localStructuralSsim.toFixed(6)),
      maskedPixels: artworkResult.maskedPixels,
      qrGeometry: artworkResult.qrMeasurement,
      structuralErrorBreakdown: artworkResult.structuralErrorBreakdown,
      largestRawMismatchRegions: artworkResult.largestRawMismatchRegions,
      regionalErrorBreakdown: artworkResult.regionalErrorBreakdown,
    },
    ...(decodedQrPayload ? { decodedQrPayload } : {}),
    output: {
      referenceCrop: `${fixture.id}-reference-crop.png`,
      dashboardPreview: `${fixture.id}-dashboard-preview.png`,
      pixelDiff: `${fixture.id}-pixel-diff.png`,
      maskedPixelDiff: `${fixture.id}-masked-pixel-diff.png`,
      structuralMask: `${fixture.id}-structural-mask.png`,
      productionArtwork: `${fixture.id}-production-artwork.png`,
      artworkReference: `${fixture.id}-artwork-reference.png`,
      artworkCurrentProduction: `${fixture.id}-artwork-current-production.png`,
      artworkPixelDiff: `${fixture.id}-artwork-pixel-diff.png`,
      artworkMaskedPixelDiff: `${fixture.id}-artwork-masked-pixel-diff.png`,
      artworkStructuralMask: `${fixture.id}-artwork-structural-mask.png`,
    },
  };
}

async function main() {
  await mkdir(outputDirectory, { recursive: true });
  const results = await Promise.all(fixtures.map(runFixture));
  await writeFile(
    resolve(outputDirectory, "similarity.json"),
    `${JSON.stringify({ outputDirectory, results }, null, 2)}\n`,
  );
  for (const result of results) {
    console.log(
      `${result.id}: raw ${(result.rawSimilarity * 100).toFixed(2)}%, structural ${(result.structuralSimilarity * 100).toFixed(2)}%`,
    );
    console.log(
      result.largestRawMismatchRegions
        .slice(0, 3)
        .map((region) => `${region.name} ${(region.rawSimilarity * 100).toFixed(2)}%`)
        .join(", "),
    );
    console.log(
      `  artwork raw ${(result.artworkComparison.rawSimilarity * 100).toFixed(2)}%, structural ${(result.artworkComparison.structuralSimilarity * 100).toFixed(2)}%`,
    );
    console.log(
      `  registration scale ${result.artworkComparison.registration.scale.toFixed(6)}, translate (${result.artworkComparison.registration.translateX.toFixed(2)}, ${result.artworkComparison.registration.translateY.toFixed(2)}), axis (${result.artworkComparison.registration.axisScale.x.toFixed(6)}, ${result.artworkComparison.registration.axisScale.y.toFixed(6)}), anisotropy ${(result.artworkComparison.registration.anisotropy * 100).toFixed(2)}%`,
    );
    console.log(
      result.artworkComparison.largestRawMismatchRegions
        .slice(0, 4)
        .map((region) => `${region.name} ${(region.rawSimilarity * 100).toFixed(2)}%`)
        .join(", "),
    );
  }
}

void main();
